export const ACCESSORY_CATEGORIES = {
  eyes: {
    id: "eyes",
    label: "Eyes",
    position: { x: 500, y: 450 },
    scale: 1,
    options: [
      {
        id: "e1",
        type: "image",
        value: "/eyes/agressive.png",
        label: "Agressive",
      },
      { id: "e2", type: "image", value: "/eyes/blasé.png", label: "Blasé" },
      { id: "e3", type: "image", value: "/eyes/blue1.png", label: "Blue 1" },
      { id: "e4", type: "image", value: "/eyes/blue2.png", label: "Blue 2" },
      { id: "e5", type: "image", value: "/eyes/cute.png", label: "Cute" },
      { id: "e6", type: "image", value: "/eyes/diams.png", label: "Diams" },
      { id: "e7", type: "image", value: "/eyes/glass2.png", label: "Glass 2" },
      { id: "e8", type: "image", value: "/eyes/glass3.png", label: "Glass 3" },
      {
        id: "e9",
        type: "image",
        value: "/eyes/hlowglass.png",
        label: "Hlow Glass",
      },
      { id: "e10", type: "image", value: "/eyes/luffy.png", label: "Luffy" },
      {
        id: "e11",
        type: "image",
        value: "/eyes/lunettes1.png",
        label: "Lunettes 1",
      },
      { id: "e12", type: "image", value: "/eyes/notmal.png", label: "Normal" },
      { id: "e13", type: "image", value: "/eyes/pink1.png", label: "Pink 1" },
      { id: "e14", type: "image", value: "/eyes/punk.png", label: "Punk" },
      { id: "e15", type: "image", value: "/eyes/red.png", label: "Red" },
      { id: "e16", type: "image", value: "/eyes/ruby.png", label: "Ruby" },
      { id: "e17", type: "image", value: "/eyes/def.png", label: "Def" },
      { id: "e18", type: "image", value: "/eyes/green_glow.png", label: "Green Glow" },
      { id: "e19", type: "image", value: "/eyes/orange_glow.png", label: "Orange Glow" },
      { id: "e20", type: "image", value: "/eyes/paper.png", label: "Paper" },
      { id: "e21", type: "image", value: "/eyes/pink_glow.png", label: "Pink Glow" },
      { id: "e22", type: "image", value: "/eyes/princess.png", label: "Princess" },
      { id: "e23", type: "image", value: "/eyes/snake.png", label: "Snake" },
    ],
  },
  mouth: {
    id: "mouth",
    label: "Mouth",
    position: { x: 500, y: 600 },
    scale: 1,
    options: [
      { id: "m1", type: "image", value: "/Mouth/angry.png", label: "Angry" },
      {
        id: "m2",
        type: "image",
        value: "/Mouth/moustache.png",
        label: "Moustache",
      },
      {
        id: "m3",
        type: "image",
        value: "/Mouth/red_lips.png",
        label: "Red Lips",
      },
      {
        id: "m4",
        type: "image",
        value: "/Mouth/gold_monster.png",
        label: "Gold Monster",
      },
      { id: "m5", type: "image", value: "/Mouth/Image.png", label: "Image" },
      { id: "m6", type: "image", value: "/Mouth/cross.png", label: "Cross" },
      { id: "m7", type: "image", value: "/Mouth/langue.png", label: "Tongue" },
      {
        id: "m8",
        type: "image",
        value: "/Mouth/crystal.png",
        label: "Crystal",
      },
      {
        id: "m9",
        type: "image",
        value: "/Mouth/surprised.png",
        label: "Surprised",
      },
      {
        id: "m10",
        type: "image",
        value: "/Mouth/villain.png",
        label: "Villain",
      },
      { id: "m11", type: "image", value: "/Mouth/gothic.png", label: "Gothic" },
      {
        id: "m12",
        type: "image",
        value: "/Mouth/cigare.png",
        label: "Cigare",
      },
      {
        id: "m13",
        type: "image",
        value: "/Mouth/tombone.png",
        label: "Tombone",
      },
      { id: "m14", type: "image", value: "/Mouth/happy.png", label: "Happy" },
      { id: "m15", type: "image", value: "/Mouth/kiss.png", label: "Kiss" },
      {
        id: "m16",
        type: "image",
        value: "/Mouth/tire_langue.png",
        label: "Tire Langue",
      },
    ],
  },
  hair: {
    id: "hair",
    label: "Hair",
    position: { x: 500, y: 200 },
    scale: 1,
    options: [
      {
        id: "h1",
        type: "image",
        value: "/hair/blond_girl.png",
        label: "Blond Girl",
      },
      {
        id: "h2",
        type: "image",
        value: "/hair/blond_short.png",
        label: "Blond Short",
      },
      {
        id: "h3",
        type: "image",
        value: "/hair/long_brown_brillant.png",
        label: "Long Brown",
      },
      { id: "h4", type: "image", value: "/hair/punk.png", label: "Punk Style" },
      {
        id: "h5",
        type: "image",
        value: "/hair/granny.png",
        label: "Granny Style",
      },
      {
        id: "h6",
        type: "image",
        value: "/hair/salt_pepper.png",
        label: "Salt & Pepper",
      },
      { id: "h7", type: "image", value: "/hair/bonnet.png", label: "Bonnet" },
      { id: "h8", type: "image", value: "/hair/cap.png", label: "Cap" },
      {
        id: "h9",
        type: "image",
        value: "/hair/couronne.png",
        label: "Couronne",
      },
      { id: "h10", type: "image", value: "/hair/cowboy.png", label: "Cowboy" },
      { id: "h11", type: "image", value: "/hair/richou.png", label: "Richou" },
      { id: "h12", type: "image", value: "/hair/black.png", label: "Black" },
      { id: "h13", type: "image", value: "/hair/brushing.png", label: "Brushing" },
      { id: "h14", type: "image", value: "/hair/durden.png", label: "Durden" },
      { id: "h15", type: "image", value: "/hair/zizou.png", label: "Zizou" },
      { id: "h16", type: "image", value: "/hair/93cap.png", label: "93 Cap" },
      { id: "h17", type: "image", value: "/hair/blue.png", label: "Blue" },
      {
        id: "h18",
        type: "image",
        value: "/hair/christmaschap.png",
        label: "Christmas Cap",
      },
      { id: "h19", type: "image", value: "/hair/xealist.png", label: "Xealist" },
      { id: "h20", type: "image", value: "/hair/volcano.png", label: "Volcano" },
      { id: "h21", type: "image", value: "/hair/fries.png", label: "Fries" },
      { id: "h22", type: "image", value: "/hair/mouss.png", label: "Mouss" },
    ],
  },
  badges: {
    id: "badges",
    label: "Badges",
    position: { x: 500, y: 500 },
    scale: 1,
    options: [
      { id: "b1", type: "image", value: "/badges/1.png", label: "Badge 1" },
      {
        id: "b1b",
        type: "image",
        value: "/badges/1_bis.png",
        label: "Badge 1 Bis",
      },
      {
        id: "b1bb",
        type: "image",
        value: "/badges/1_bis_bis.png",
        label: "Badge 1 Bis Bis",
      },
      { id: "b2", type: "image", value: "/badges/2.png", label: "Badge 2" },
      {
        id: "b2b",
        type: "image",
        value: "/badges/2_bis.png",
        label: "Badge 2 Bis",
      },
      {
        id: "b2bb",
        type: "image",
        value: "/badges/2_bis_bis.png",
        label: "Badge 2 Bis Bis",
      },
      { id: "b3", type: "image", value: "/badges/3.png", label: "Badge 3" },
      {
        id: "b3b",
        type: "image",
        value: "/badges/3_bis.png",
        label: "Badge 3 Bis",
      },
      {
        id: "b3bb",
        type: "image",
        value: "/badges/3_bis_bis.png",
        label: "Badge 3 Bis Bis",
      },
      { id: "b4", type: "image", value: "/badges/4.png", label: "Badge 4" },
      {
        id: "b4b",
        type: "image",
        value: "/badges/4_bis.png",
        label: "Badge 4 Bis",
      },
      {
        id: "b4bb",
        type: "image",
        value: "/badges/4_bis_bis.png",
        label: "Badge 4 Bis Bis",
      },
      { id: "b5", type: "image", value: "/badges/5.png", label: "Badge 5" },
      {
        id: "b5b",
        type: "image",
        value: "/badges/5_bis.png",
        label: "Badge 5 Bis",
      },
      {
        id: "b5bb",
        type: "image",
        value: "/badges/5_bis_bis.png",
        label: "Badge 5 Bis Bis",
      },
      { id: "b6", type: "image", value: "/badges/6.png", label: "Badge 6" },
      {
        id: "b6b",
        type: "image",
        value: "/badges/6_bis.png",
        label: "Badge 6 Bis",
      },
      {
        id: "b6bb",
        type: "image",
        value: "/badges/6_bis_bis.png",
        label: "Badge 6 Bis Bis",
      },
      { id: "b7", type: "image", value: "/badges/7.png", label: "Badge 7" },
      {
        id: "b7b",
        type: "image",
        value: "/badges/7_bis.png",
        label: "Badge 7 Bis",
      },
      {
        id: "b7bb",
        type: "image",
        value: "/badges/7_bis_bis.png",
        label: "Badge 7 Bis Bis",
      },
      { id: "b8", type: "image", value: "/badges/8.png", label: "Badge 8" },
      {
        id: "b8b",
        type: "image",
        value: "/badges/8_bis.png",
        label: "Badge 8 Bis",
      },
      {
        id: "b8bb",
        type: "image",
        value: "/badges/8_bis_bis.png",
        label: "Badge 8 Bis Bis",
      },
      {
        id: "b9bb",
        type: "image",
        value: "/badges/9_bis_bis.png",
        label: "Badge 9 Bis Bis",
      },
      {
        id: "bleader",
        type: "image",
        value: "/badges/leader_bis_bis.png",
        label: "Leader Badge",
      },
    ],
  },

  accessories: {
    id: "accessories",
    label: "Accessories",
    position: { x: 200, y: 500 }, // Left side
    scale: 1,
    options: [
      {
        id: "acc1",
        type: "image",
        value: "/accessories/sceptre.png",
        label: "Sceptre",
      },
      {
        id: "acc2",
        type: "image",
        value: "/accessories/bic.png",
        label: "Bic",
      },
      {
        id: "acc3",
        type: "image",
        value: "/accessories/buybtc.png",
        label: "Buy BTC",
      },
      {
        id: "acc4",
        type: "image",
        value: "/accessories/canard.png",
        label: "Canard",
      },
      {
        id: "acc5",
        type: "image",
        value: "/accessories/pistol.png",
        label: "Pistol",
      },
      {
        id: "acc6",
        type: "image",
        value: "/accessories/rockymano.png",
        label: "Rocky Mano",
      },
      {
        id: "acc7",
        type: "image",
        value: "/accessories/btc.png",
        label: "BTC",
      },
      {
        id: "acc8",
        type: "image",
        value: "/accessories/coca.png",
        label: "Coca",
      },
      {
        id: "acc9",
        type: "image",
        value: "/accessories/crystal_ball.png",
        label: "Crystal Ball",
      },
      {
        id: "acc10",
        type: "image",
        value: "/accessories/jack.png",
        label: "Jack",
      },
      {
        id: "acc11",
        type: "image",
        value: "/accessories/joker.png",
        label: "Joker",
      },
      {
        id: "acc12",
        type: "image",
        value: "/accessories/ledger.png",
        label: "Ledger",
      },
      {
        id: "acc13",
        type: "image",
        value: "/accessories/mainvernis.png",
        label: "Main Vernis",
      },
      {
        id: "acc14",
        type: "image",
        value: "/accessories/phone.png",
        label: "Phone",
      },
      {
        id: "acc15",
        type: "image",
        value: "/accessories/sword.png",
        label: "Sword",
      },
      {
        id: "acc16",
        type: "image",
        value: "/accessories/ukulele.png",
        label: "Ukulele",
      },
    ],
  },
  clothes: {
    id: "clothes",
    label: "Clothes",
    position: { x: 500, y: 600 },
    scale: 1,
    options: [
      { id: "c1", type: "image", value: "/Clothes/om.png", label: "OM" },
      {
        id: "c2",
        type: "image",
        value: "/Clothes/bandana.png",
        label: "Bandana",
      },
      {
        id: "c3",
        type: "image",
        value: "/Clothes/chemise.png",
        label: "Chemise",
      },
      {
        id: "c4",
        type: "image",
        value: "/Clothes/costume.png",
        label: "Costume",
      },
      { id: "c5", type: "image", value: "/Clothes/cuir.png", label: "Cuir" },
      { id: "c6", type: "image", value: "/Clothes/king.png", label: "King" },
      { id: "c7", type: "image", value: "/Clothes/punk.png", label: "Punk" },
      { id: "c8", type: "image", value: "/Clothes/china.png", label: "China" },
      { id: "c9", type: "image", value: "/Clothes/egypt.png", label: "Egypt" },
      { id: "c10", type: "image", value: "/Clothes/fcb.png", label: "FCB" },
      {
        id: "c11",
        type: "image",
        value: "/Clothes/indonesia.png",
        label: "Indonesia",
      },
      {
        id: "c12",
        type: "image",
        value: "/Clothes/manchester.png",
        label: "Manchester",
      },
      {
        id: "c13",
        type: "image",
        value: "/Clothes/nigeria.png",
        label: "Nigeria",
      },
      { id: "c14", type: "image", value: "/Clothes/psg.png", label: "PSG" },
      { id: "c15", type: "image", value: "/Clothes/real.png", label: "Real" },
      {
        id: "c16",
        type: "image",
        value: "/Clothes/turkish.png",
        label: "Turkish",
      },
      {
        id: "c17",
        type: "image",
        value: "/Clothes/dentelle.png",
        label: "Dentelle",
      },
      {
        id: "c18",
        type: "image",
        value: "/Clothes/princess.png",
        label: "Princess",
      },
    ],
  },
  fonds: {
    id: "fonds",
    label: "Backgrounds",
    position: { x: 500, y: 500 },
    scale: 1,
    options: [
      { id: "f1", type: "image", value: "/fonds/base.jpg", label: "Base" },
      {
        id: "f2",
        type: "image",
        value: "/fonds/mountain.jpg",
        label: "Mountain",
      },
      { id: "f3", type: "image", value: "/fonds/beach.jpg", label: "Beach" },
      { id: "f4", type: "image", value: "/fonds/field.jpg", label: "Field" },
      { id: "f5", type: "image", value: "/fonds/forest.jpg", label: "Forest" },
      { id: "f6", type: "image", value: "/fonds/ny.jpg", label: "New York" },
      { id: "f7", type: "image", value: "/fonds/sea.jpg", label: "Sea" },
      {
        id: "f8",
        type: "image",
        value: "/fonds/volcano.jpg",
        label: "Volcano",
      },
      {
        id: "f9",
        type: "image",
        value: "/fonds/cinema.jpg",
        label: "Cinema",
      },
      {
        id: "f10",
        type: "image",
        value: "/fonds/ruelle.jpg",
        label: "Ruelle",
      },
      { id: "fcolor", type: "color", value: "#FFFFFF", label: "Custom Color" },
    ],
  },
};
